export const UPDATE_HEADER_CAROUSEL_DATA = 'APP_UPDATE_HEADER_CAROUSEL_DATA';

export const UPDATE_IS_FETCHING_PRODUCTS = 'HP_UPDATE_IS_FETCHING_PRODUCTS';
export const UPDATE_PRODUCTS_LIST = 'HP_UPDATE_PRODUCTS_LIST';

export const UPDATE_IS_FETCHING_DETAILS = 'PDP_UPDATE_IS_FETCHING_DETAILS';
export const UPDATE_PRODUCT_DETAILS = 'PDP_UPDATE_PRODUCT_DETAILS';